name: Build and publish
on:
  workflow_dispatch:
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build_go_binary_and_release:
    name: Build go binary and release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15.5

      - name: Build binary
        run: |
          env GOOS=linux GOARCH=amd64 go build -o dist/linux
          env GOOS=windows GOARCH=amd64 go build -o dist/windows
          env GOOS=darwin GOARCH=amd64 go build -o dist/macos
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: ""
          draft: false
          prerelease: false