name: Build and publish
on:
  workflow_dispatch:
# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  build_go_binary_and_release:
    if: startsWith( ${{ github.ref_name }}, 'v')
    name: Build go binary and release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15.5

      - name: Build binary
        run: |
          env GOOS=linux GOARCH=amd64 go build -o dist/linux
          env GOOS=windows GOARCH=amd64 go build -o dist/windows
          env GOOS=darwin GOARCH=amd64 go build -o dist/macos

      - name: Output vars
        id: vars
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IS_PRE_RELEASE=false

          NEXT_VERSION="${{ github.ref_name }}"

          echo "::set-output name=is-pre-release::$IS_PRE_RELEASE"
          echo "::set-output name=next-version::$NEXT_VERSION"

      - name: Create tag
        run: |
          git config --global user.email "${{ vars.TESTER_EMAIL }}"
          git config --global user.name "${{ vars.TESTER }}"
          git add .
          git commit -m 'release: ${{ steps.vars.outputs.next-version }}'
          git tag ${{ steps.vars.outputs.next-version }}
          git push origin --tags

          if [[ "${{ steps.vars.outputs.is-pre-release }}" == false ]]; then
            MAJOR_TAG=$(echo "${{ steps.vars.outputs.next-version }}" | sed "s/\..*//")

            git tag $MAJOR_TAG -f -a -m "Update tag with version ${{ steps.vars.outputs.next-version }}"
            git push origin tag $MAJOR_TAG --force
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.next-version }}
          release_name: ${{ steps.vars.outputs.next-version }}
          body: ""
          draft: false
          prerelease: ${{ steps.vars.outputs.is-pre-release }}